project_name: LMU
pkg_name: lmu
repo_name: lmu
description: Legrenge Memory Units

copyright_start: 2019

license_rst: {}

contributing_rst: {}

contributors_rst: {}

setup_py:
  install_req:  
    - nengolib>=0.5.1
    - keras>=2.2.4 
    - tensorflow>=2.0.0
  doc_req:
    - matplotlib>=3.0.2
    - IPython>=7.2.0
    - notebook>=5.7.4
    - seaborn>=0.9.0
  optional_req:
    - scipy
  classifiers:
    - "Development Status :: 3 - Alpha"
    - "Framework :: Nengo"
    - "Intended Audience :: Science/Research"
    - "License :: Free for non-commercial use"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python "
    - "Programming Language :: Python :: 3.5"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Topic :: Scientific/Engineering "
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

setup_cfg:
  flake8:
    exclude:
      - lmu/__init__.py
  pylint:
    disable:
      - imported-but-unused 

travis_yml:
  python: 3.5
  global_vars:
    NUMPY: numpy
  jobs:
    - script: static
  pypi_user: studywolf

ci_scripts:
  - template: static

codecov_yml: {}
