project_name: LMU
pkg_name: lmu
repo_name: lmu
description: Legrenge memory units

copyright_start: 2020

license_rst: {}

contributing_rst: {}

contributors_rst: {}

setup_py:
  install_req:
    - keras>=2.2.4
    - tensorflow>=2.0.0
    - torch>=1.1.0
    - scikit-learn>=0.20.1
    - matplotlib>=3.0.2
    - IPython>=7.2.0
    - notebook>=5.7.4
    - seaborn>=0.9.0
    - scipy
    - nengolib>=0.5.1
    - nengo>=2.8.0,<3.0
    - phased-lstm-keras
  tests_req:
    - pytest>=4.3.0
  classifiers:
    - "Development Status :: 3 - Alpha"
    - "Framework :: Nengo"
    - "Intended Audience :: Science/Research"
    - "License :: Free for non-commercial use"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python "
    - "Programming Language :: Python :: 3.5"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Topic :: Scientific/Engineering "
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

travis_yml:
  python: 3.6
  global_vars:
    NUMPY: numpy
  jobs:
    - script: static
  pypi_user: studywolf

ci_scripts:
  - template: static

codecov_yml: {}
